### ISSUE TITLE
A list of route that use more portal with difficulty rating ?

### ISSUE THREAD

**Issue by Oryn-Goia** [pektezol/LeastPortalsHub#13]
Idk, it would most likely be similar to LP history, just with difficulty rating in order to "avoid the what should i play next question"

**Comment by pektezol** [comment]
Though a while about this, we can do a survey from top lp players to give ratings for each map, then order them to a list. After that, on user profiles, we can suggest the next lowest rated map that the user has not completed yet. Sick idea, need data.

**Comment by Oryn-Goia** [comment]
It's hard to be objective as a top player for lower diff routes. I do find bomb flings much easier than most people think it is, and like, funnel intro oob will be thought super easy, and inbounds super hard, where in fact both are probably as easy.
We'd need lots of answers xD

**Comment by Oryn-Goia** [comment]
Tomorrow I'll make a list of all maps, with several different portal amount (reasonable ones) and once you confirm it we can make it a poll "rate this from 1 very easy to 10 very hard, and I could probably get an idea of the videos explaining the different routes

**Comment by pektezol** [comment]
Oh you want to include non wr maps as well? We should prob make it from 1 to 100 or smth if we have that much entries.

**Comment by Oryn-Goia** [comment]
I was thinking 1-10, cause how can you estimate a map is difficulty 13 and a map is difficulty 14 ?
I know the issue you're thinking about, but if we take the average of the 10ish people who do the poll, assuming they were honest, we should get decimal numbers that "should" be different for each maps, except the extremes, like a 1* would probably be 1* for everyone and a 10* would probably be 10* for everyone

**Comment by Oryn-Goia** [comment]
So far I have 16 people who answered the poll among which there are top LP players, average players, and some I'd consider more beginners. I don't know if more people will answer. Because that's how many people I'd estimate to be active and interested in LP currently.

**Comment by pektezol** [comment]
Closing since stale, will implement map route rating.
