### ISSUE TITLE
Community Rating of maps

### ISSUE THREAD

**Issue by Oryn-Goia** [pektezol/LeastPortalsHub#16]
Similar to #13  
We could add the way for a community to vote on how difficult the map was, either on the page of the map, or, to avoid any stupid trolls like seen on the google form, after demo submission (so if the demo is cheated, we could cancel the score and therefore cancel their vote)
It would also involve a unique vote per route per person

**Comment by Oryn-Goia** [comment]
How am i so stupid, I meant #13 xD

**Comment by Oryn-Goia** [comment]
Last time i edited it didn't fix it in the other issue

**Comment by pektezol** [comment]
Ah yeah, rip

**Comment by pektezol** [comment]
Closing since stale, will implement map route rating.
