### ISSUE TITLE
Allowing to search a user by ID/username, even if they didn't complete all the LP

### ISSUE THREAD

**Issue by Oryn-Goia** [pektezol/LeastPortalsHub#7]
If someone has retired, or hasn't submitted demos (yet), they can see what they are missing. It would require to get their data from their profile, including if they never played P2 (we don't know what people may search for).

**Comment by pektezol** [comment]
Would this include people who were never logged into this website? Right now, I'm thinking of "creating" a new user and fetching their data when they log in to the site for the first time, and don't care about people that didn't join.

**Comment by Oryn-Goia** [comment]
Yeah that. I was thinking if you don't have every LP (in current boards you don't appear) so it was to look up for yourself. But a search option could technically be used for someone not registered in the site at all. Tho it might be worthless to do it for them
(would also be great to bypass this for retired people who don't play anymore, so they are still added to the ranks)

**Comment by pektezol** [comment]
I guess certain/retired people can be added to the site manually? With that way we can "bypass it". Other than that, I don't think we should have a global search for people not registered. Thoughts?

**Comment by pektezol** [comment]
Alright then, it's decided.
